package com.ams.hrms.report;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

/**
 * Fully materialized report (spec section 27): identity and parameter echo,
 * column metadata, typed data rows, an optional totals row and generation
 * provenance. Writers ({@link PdfReportWriter}, {@link ExcelReportWriter})
 * and the preview table all consume this one structure.
 *
 * @param title        report title
 * @param subtitle     human-readable echo of the applied filters
 * @param columns      column metadata
 * @param rows         data rows; cell types are String, BigDecimal,
 *                     LocalDate or null
 * @param totalsRow    optional trailing totals row matching {@code columns}
 * @param generatedBy  username that produced the report
 * @param generatedAt  production timestamp
 * @param companyName  company header text for exports
 */
public record ReportResult(
        String title,
        String subtitle,
        List<ReportColumn> columns,
        List<Object[]> rows,
        Object[] totalsRow,
        String generatedBy,
        LocalDateTime generatedAt,
        String companyName) {

    public ReportResult {
        columns = List.copyOf(columns);
        rows = List.copyOf(rows);
    }

    public boolean hasData() {
        return !rows.isEmpty();
    }

    public int dataRowCount() {
        return rows.size();
    }

    /** Footer line used by both writers. */
    public String footerText() {
        return "Generated by " + generatedBy + " on "
                + generatedAt.format(DateTimeFormatter.ofPattern(
                        "dd MMM uuuu HH:mm", Locale.ENGLISH));
    }
}
