package com.ams.hrms.report;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Path;
import java.time.LocalDate;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Recruitment PDF generators (vacancy requisition, offer letter), all fully
 * offline (no database).
 */
class RecruitmentPdfGeneratorsTest {

    @TempDir
    Path tempDir;

    private static VacancyPdfGenerator.VacancyData vacancyData() {
        return new VacancyPdfGenerator.VacancyData(
                "Test Company", "No. 1 Main Road, Yangon",
                "VAC-0019", "Software Developer",
                "Information Technology", "Software Developer",
                "FULL_TIME", "OPEN",
                2, 1,
                new BigDecimal("1500.00"), new BigDecimal("3000.00"), "USD",
                LocalDate.of(2026, 8, 1), LocalDate.of(2026, 9, 30),
                "Build web applications with the team.",
                "Java experience. Spring Boot. SQL.",
                "admin", "2026-08-25");
    }

    private static OfferPdfGenerator.OfferData offerData(boolean draft) {
        return new OfferPdfGenerator.OfferData(
                "Test Company", "No. 1 Main Road, Yangon",
                "OFF-0010", "APP-0008",
                "Ronal Soe", "SOFTWARE_DEVELOPER",
                new BigDecimal("2000.00"), "USD",
                LocalDate.of(2026, 8, 20), LocalDate.of(2026, 9, 3),
                LocalDate.of(2026, 10, 1),
                draft ? "DRAFT" : "SENT", draft,
                "admin", "2026-08-25");
    }

    private String textOf(Path file) throws IOException {
        try (PDDocument document = Loader.loadPDF(file.toFile())) {
            return new PDFTextStripper().getText(document);
        }
    }

    @Test
    @DisplayName("Vacancy PDF contains header, info block, salary range and sections")
    void vacancyPdfContainsKeyContent() throws Exception {
        Path output = tempDir.resolve("vacancy_VAC-0019.pdf");
        VacancyPdfGenerator.generate(vacancyData(), output);

        assertThat(output).exists();
        String text = textOf(output);
        assertThat(text)
                .contains("Test Company")
                .contains("Job Vacancy")
                .contains("VAC-0019")
                .contains("Software Developer")
                .contains("Full Time")
                .contains("SALARY RANGE")
                .contains("1,500.00 - 3,000.00 USD")
                .contains("JOB DESCRIPTION")
                .contains("REQUIREMENTS")
                .contains("Generated by admin");
    }

    @Test
    @DisplayName("Vacancy PDF paginates long text onto multiple pages")
    void vacancyPdfPaginatesLongText() throws Exception {
        VacancyPdfGenerator.VacancyData data = new VacancyPdfGenerator.VacancyData(
                "Test Company", "Address", "VAC-0001", "Title",
                "Department", "Position", "FULL_TIME", "OPEN",
                1, 0, null, null, "USD", null, null,
                "Line of description text. ".repeat(400),
                "Line of requirement text. ".repeat(400),
                "admin", "2026-08-25");
        Path output = tempDir.resolve("vacancy_long.pdf");
        VacancyPdfGenerator.generate(data, output);

        try (PDDocument document = Loader.loadPDF(output.toFile())) {
            assertThat(document.getNumberOfPages()).isGreaterThan(1);
        }
    }

    @Test
    @DisplayName("Offer letter contains salutation, terms, salary and signatures")
    void offerPdfContainsKeyContent() throws Exception {
        Path output = tempDir.resolve("offer_OFF-0010.pdf");
        OfferPdfGenerator.generate(offerData(false), output);

        String text = textOf(output);
        assertThat(text)
                .contains("OFFER OF EMPLOYMENT")
                .contains("Dear Ronal Soe")
                .contains("OFF-0010")
                .contains("2,000.00 USD")
                .contains("Valid Until")
                .contains("Joining Date")
                .contains("Authorised Signatory")
                .contains("Accepted by candidate");
        assertThat(text).doesNotContain("DRAFT");
    }

    @Test
    @DisplayName("Draft offer carries a DRAFT watermark and draft notice")
    void draftOfferCarriesWatermark() throws Exception {
        Path output = tempDir.resolve("offer_draft.pdf");
        OfferPdfGenerator.generate(offerData(true), output);

        String text = textOf(output);
        assertThat(text)
                .contains("DRAFT")
                .contains("draft and has not yet been sent");
    }

    @Test
    @DisplayName("Both generators render straight to bytes for printing")
    void generatorsProduceBytes() throws Exception {
        byte[] vacancy = VacancyPdfGenerator.generate(vacancyData());
        byte[] offer = OfferPdfGenerator.generate(offerData(false));

        assertThat(vacancy).isNotEmpty();
        assertThat(new String(vacancy, 0, 5)).isEqualTo("%PDF-");
        assertThat(new String(offer, 0, 5)).isEqualTo("%PDF-");

        try (PDDocument document = Loader.loadPDF(vacancy)) {
            assertThat(document.getNumberOfPages()).isEqualTo(1);
        }
        try (PDDocument document = Loader.loadPDF(offer)) {
            assertThat(document.getNumberOfPages()).isEqualTo(1);
        }
    }
}
